"""create_documents_and_validations_tables

Revision ID: aa82d1ae51d1
Revises: dc66dee4f4c1
Create Date: 2026-09-25 15:22:24.033543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa82d1ae51d1'
down_revision: Union[str, Sequence[str], None] = 'dc66dee4f4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
